services:
  - type: web
    name: orbit-backend
    env: node
    plan: free
    region: singapore # or oregon / frankfurt closest to aws-ap-south-1
    buildCommand: npm install && npx prisma generate
    startCommand: npm run start
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        sync: false # Set to your CockroachDB connection string in Render Dashboard
      - key: PORT
        value: 5000
